### ISSUE TITLE
Renaming from CAPS to no CAPS

### ISSUE THREAD

**Issue by FranciscoSE** [Jojoshua/auto-rename-file#1]
Hi,
I'm trying to rename from .XML to .xml, using the following configuration:

```  
"autoRenameFile": {
              "config": [
                {
                  "from": ".XML",
                  "to": ".xml"
                }
              ]
            }
```

The renaming fails with the following error:
![image](https://github.com/Jojoshua/auto-rename-file/assets/32928069/d48ae24e-8de8-4c95-bdcf-e1b3ee5937a2)

**Comment by Jojoshua** [comment]
VSCode renameFile is returning that message. Even trying to use overwrite it still persists. This isn't the real use case for the extension though.
